name: "fetch-LMU"
on:
  workflow_dispatch:
  # schedule:
    # - cron: "30 7,8,9,10,11,12,13,14,21,22 * * *"
  
jobs:
  fetch-LMU:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        
    - name: Install dependencies
      run: python3 -m pip install pandas
      
    - name: Fetch LMU
      run: python3 ./code/fetch_nowcasts/fetch-LMU.py

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        commit-message: Update nowcasts (LMU)
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: fetch-LMU
        delete-branch: true
        title: 'Update nowcasts (LMU)'
        body: |
          Update nowcasts
        labels: |
          automated pr
