name: "fill-RKI-data"
on:
  workflow_dispatch:
  
jobs:
  fill-RKI-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 
        
    - name: Install dependencies
      run: python3 -m pip install pandas requests pathlib
      
    - name: Fill RKI data
      run: python3 ./code/fill_missing.py

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - RKI Update"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/hospitalization-nowcast-hub.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit -m "Add missing RKI data"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
